config/routes.rb
Messaging::Engine.routes.draw do

  resources :messages do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end
  post 'search' => 'messages#search'
  root :to => 'messages#index'
end

app/models/messaging/message.rb
module Messaging
  class Message
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming

    attr_accessor :recipients, :subject, :body, :conversation_id, :attachment

    validates :recipients, presence: true
    validates :subject, presence: true
    validates :body, presence: true

    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end

    def persisted?
      false
    end


    def recipients
      @recipient_list
    end

    def recipients=(string='')
      @recipient_list = []
      string.split(',').each do |s|
        @recipient_list << MessagingUser.find_by_username!(s.strip) unless s.blank?
      end
    end
  end
end

app/controllers/messaging/application_controller.rb
class Messaging::ApplicationController < ApplicationController
    before_filter :authenticate_user!
end

app/controllers/messaging/messages_controller.rb
module Messaging
  class MessagesController < Messaging::ApplicationController
    def index
      @box = params[:box] || 'inbox'
      @messages = current_user.mailbox.inbox if @box == 'inbox'
      @messages = current_user.mailbox.sentbox if @box == 'sent'
      @messages = current_user.mailbox.trash if @box == 'trash'
    end

    def new
      @message = Message.new
    end

    def create
      @message = Message.new params[:message]

      if @message.conversation_id
        @conversation = Conversation.find(@message.conversation_id)
        unless @conversation.is_participant?(current_user)
          flash[:alert] = "You do not have permission to view that conversation."
          return redirect_to root_path
        end
        receipt = current_user.reply_to_conversation(@conversation, @message.body, nil, true, true, @message.attachment)
      else
        unless @message.valid?
          return render :new
        end
        receipt = current_user.send_message(@message.recipients, @message.body, @message.subject, true, @message.attachment)
      end
      flash[:notice] = "Message sent."

      redirect_to message_path(receipt.conversation)
    end

    def show
      @conversation = Conversation.find_by_id(params[:id])
      unless @conversation.is_participant?(current_user)
        flash[:alert] = "You do not have permission to view that conversation."
        return redirect_to root_path
      end
      @message = Message.new conversation_id: @conversation.id
      current_user.mark_as_read(@conversation)
    end

    def trash
      conversation = Conversation.find_by_id(params[:id])
      if conversation
        current_user.trash(conversation)
        flash[:notice] = "Message sent to trash."
      else
        conversations = Conversation.find(params[:conversations])
        conversations.each { |c| current_user.trash(c) }
        flash[:notice] = "Messages sent to trash."
      end
      redirect_to messages_path(box: params[:current_box])
    end

    def untrash
      conversation = Conversation.find(params[:id])
      current_user.untrash(conversation)
      flash[:notice] = "Message untrashed."
      redirect_to messages_path(box: 'inbox')
    end

    def search
      @search = params[:search]
      @messages = current_user.search_messages(@search)
      render :index
    end
  end
end

app/helpers/messaging/application_helper.rb
module Messaging
  module ApplicationHelper
  end
end

app/views/messaging/messages/index.html.haml
= stylesheet_link_tag "messaging/application"
= javascript_include_tag "messaging/adapt"
= javascript_include_tag "messaging/application"

.container
  .header-section.span12
  - if @search
    %h2 Search results for '#{@search}'
  - if @box == 'inbox'
    %h2 Inbox
  - if @box == 'sent'
    %h2 Sent
  - if @box == 'trash'
    %h2 Trash
  = form_tag trash_messages_path, method: :delete do
    = hidden_field_tag 'current_box', @box
    %table#box
      %tr
        - unless @box == 'trash'
          %th
        %th Sender
        %th Subject
        %th Messages
        %th
      - @messages.each do |m|
        %tr{ class: "#{ 'unread' if m.is_unread?(current_user) }" }
          - unless @box == 'trash'
            %td= check_box_tag '', m.id, false, class: 'delete_multiple_checkbox', name: "conversations[]"
          %td= link_to m.last_sender.email_display_name, message_path(m)
          %td= link_to m.subject, message_path(m)
          %td= link_to m.count_messages, message_path(m)
          %td= link_to truncate(m.last_message.body), message_path(m)
    - unless @box == 'trash'
      = submit_tag "Delete checked messages", id: 'delete_multiple_button'

app/views/messaging/messages/new.html.haml
= stylesheet_link_tag "messaging/application"
= javascript_include_tag "messaging/adapt"
= javascript_include_tag "messaging/application"

.container
  .header-section.span12
  %h2 Compose
  #compose
    = simple_form_for @message do |f|
      = f.label :recipients, required: false
      = f.input_field :recipients, data: { autocomplete_source: MessagingUser.all.map(&:name) }
      = f.label :subject, required: false
      = f.input_field :subject
      = f.label :body, required: false
      = f.input_field :body, as: :text
      = f.input :attachment, as: :file
      = f.button :submit, 'Send message'

app/views/messaging/messages/show.html.haml
= stylesheet_link_tag "messaging/application"
= javascript_include_tag "messaging/adapt"
= javascript_include_tag "messaging/application"

.container
  .header-section.span12
  #message_header.span8.offset1
    .inbox= link_to "Inbox", messages_path
    .subject= @conversation.subject
    #actions
      - if @conversation.is_trashed?(current_user)
        = link_to "Untrash", untrash_message_path(@conversation), class: :button, method: :post
      - else
        = link_to "Trash", trash_message_path(@conversation), class: :button, method: :delete
  %ul#conversation.offset1
    - @conversation.messages.each do |message|
      %li
        .thumbnail.span1
          - if message.sender == current_user
            = image_tag message.sender.avatar.url
            .date= message.created_at.strftime("%b #{message.created_at.day}")
        .body.span6
          = message.body
          - if message.attachment.url
            .attachment
              = link_to message.attachment_identifier, message.attachment.url
        .thumbnail.span1
          - if message.sender != current_user
            = image_tag message.sender.avatar.url
            .date= message.created_at.strftime("%b #{message.created_at.day}")
    %li
      #reply.span6.offset1
        = simple_form_for @message do |f|
          = f.input :conversation_id, as: :hidden
          = f.label :body, label: 'Reply', required: false
          = f.input_field :body, as: :text, label: 'Reply', rows: 10
          = f.input :attachment, as: :file
          = f.button :submit, 'Send', class: "btn btn-primary"